PATH_TO_ASSIGNMENTS = None  # "./input_handling/inno_assignments.json"
PATH_TO_SCHEDULE = "./input_handling/inno_number_of_classes.json"
NUMBER_OF_ASSIGNMENTS = 15
TRACK = None  # "DS"
STUDY_YEAR = None  # "BS2"
POPULATION_SIZE: int = 1000
ELITE_SIZE: int = 100
MUTATION_RATE: float = 0.1
CROSSOVER_RATE: float = 0.5
EARLY_STOP: int = 3
NUM_OF_RUNS: int = 50
