PATH_TO_ASSIGNMENTS = "./input_handling/inno_assignments.json"
PATH_TO_SCHEDULE = "./input_handling/inno_number_of_classes.json"
TRACK = "DS"
STUDY_YEAR = "BS2"
POPULATION_SIZE: int = 1000
ELITE_SIZE: int = 100
MUTATION_RATE: float = 0.5
CROSSOVER_RATE: float = 0.5
EARLY_STOP: int = 100
NUM_OF_RUNS: int = 50
